// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxrtggyhgtlrvztzkkdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4cnRnZ3loZ3RscnZ6dHpra2R3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5NDgzNDAsImV4cCI6MjA3ODUyNDM0MH0.C9xZhK6JAbwkVWanbAyqanr6NXd7YkkNJaU1ZWVuEkQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});